language: node_js
node_js:
  - "11.13.0"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod --base-href https://ethanmsmith.github.io/
deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  local_dir: dist
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master